"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.cController = exports.pController = exports.uController = exports.bookingController = exports.followController = void 0;
const userController_1 = __importDefault(require("../../controller/userController"));
const UserUseCase_1 = __importDefault(require("../../useCase/UserUseCase"));
const hashPassword_1 = __importDefault(require("../utils/hashPassword"));
const jwt_1 = __importDefault(require("../utils/jwt"));
const userRepository_1 = __importDefault(require("../repository/userRepository"));
const cloudinary_1 = __importDefault(require("../utils/cloudinary"));
const otpGenerate_1 = __importDefault(require("../utils/otpGenerate"));
const sendMail_1 = __importDefault(require("../utils/sendMail"));
const postRepository_1 = __importDefault(require("../repository/postRepository"));
const propertyContrller_1 = __importDefault(require("../../controller/propertyContrller"));
const roomRepository_1 = __importDefault(require("../repository/roomRepository"));
const followController_1 = __importDefault(require("../../controller/followController"));
const FollowUseCase_1 = __importDefault(require("../../useCase/FollowUseCase"));
const followRepository_1 = __importDefault(require("../repository/followRepository"));
const bookingController_1 = __importDefault(require("../../controller/bookingController"));
const bookingUseCase_1 = __importDefault(require("../../useCase/bookingUseCase"));
const BookingRepository_1 = __importDefault(require("../repository/BookingRepository"));
const ChatRepository_1 = __importDefault(require("../repository/ChatRepository"));
const ChatUserCase_1 = __importDefault(require("../../useCase/ChatUserCase"));
const chatController_1 = __importDefault(require("../../controller/chatController"));
const cloudinary = new cloudinary_1.default();
const generateOTP = new otpGenerate_1.default();
const sendEmail = new sendMail_1.default();
const Jwt = new jwt_1.default();
const hashPass = new hashPassword_1.default();
const userRepository = new userRepository_1.default();
const postRepository = new postRepository_1.default();
const roomRepository = new roomRepository_1.default();
const followRepository = new followRepository_1.default();
const bookingRepository = new BookingRepository_1.default();
const ChatRepo = new ChatRepository_1.default();
const usercase = new UserUseCase_1.default(followRepository, userRepository, postRepository, roomRepository, hashPass, Jwt, cloudinary, generateOTP, sendEmail);
const fUsecase = new FollowUseCase_1.default(followRepository, userRepository);
const CUserCase = new ChatUserCase_1.default(ChatRepo);
const bUseCase = new bookingUseCase_1.default(bookingRepository);
exports.followController = new followController_1.default(fUsecase);
exports.bookingController = new bookingController_1.default(bUseCase);
exports.uController = new userController_1.default(usercase);
exports.pController = new propertyContrller_1.default(usercase);
exports.cController = new chatController_1.default(CUserCase);
